<!--% Voici un exemple de modèle pour relever le challenge "wine". Copiez ce document sous le nom de votre propre modèle dans le sous-dossier `docs`, éditez-le, développez votre modèle et soumettez vos résultats (voir aussi README.md). Bonnes chances ! -->

<!--% Donner un nom à votre modèle ici (pour plus de facilité, utilisez le même nom que celui que vous avez donné à ce fichier .Rmd). N'OUBLIEZ PAS DE MODIFIER CE NOM A CHAQUE NOUVELLE ITERATION et utilisez uniquement des lettres a-z, A-Z, des chiffres 0-9, un trait souligné (_) ou un signe moins (-). -->

```{r model_name, echo=FALSE}
model_name <- "adl_simple"
```

<!--% Indiquez votre login GitHub ci-dessous (remplacer 'login' par votre propre login Github). -->

```{r authors_logins, echo=FALSE}
authors_logins <- "login"
```

<!--% Ne TOUCHEZ PAS à l'entête YAML ci-dessous : elle sera générée automatiquement à partir des autres informations du document. -->

---
title: "`r paste(model_name, sub("^[^-]+-(.*)$", "\\1", sub("\\.git$", "", basename(usethis::git_remotes()$origin))), sep = " - ")`"
date: "`r Sys.time()`"
author: "`r authors_logins`"
output: html_notebook
---

## Résumé

<!--% Décrivez ici dans les grandes lignes (2-3 phrases max) les options mises en œuvre dans votre modèle pour en augmenter les performances par rapport au modèle de base `adl_simple`. -->

## Description des données

<!--% Vous ne devez rien changer dans le chunk suivant. -->

```{r setup, echo=FALSE,include=FALSE}
SciViews::R("ml", lang = "fr")
repos <- sub("\\.git$", "", basename(usethis::git_remotes()$origin))

# Importation des deux jeux de données
wine <- read(here::here("data/wine.rds"))
wine2 <- read(here::here("data/wine2.rds"))
```

<!--% Effectuez ici les statistiques descriptives qui vous sont nécessaires pour appréhender les données, sans toutefois vous éterniser trop dessus (20min max). -->

...


## Apprentissage

<!--% Placez ici le code en phase d'apprentissage et commentez-le brièvement. TRES IMPORTANT : appelez toujours votre modèle `my_model` dans le code ci-dessous, pas d'autre nom ! -->

```{r learning}
set.seed(3643) # ATTENTION: utilisez ici un nombre différent pour chaque modèle !
my_model <- mlLda(data = wine, quality ~ .)
```

## Test

<!--% Placez ici le code concernant la phase de test des performances de votre modèle avec un bref commentaire. -->

```{r testing}
conf <- confusion(cvpredict(my_model, cv.k = 10), wine$quality)
plot(conf)
summary(conf)
```

commentaire...

## Soumission du modèle

<!--% Pour déployer votre modèle sur `wine2` et enregistrer votre classification dans `results/<repos>__<model_name>.rds`, exécutez le chunk suivant SANS LE MODIFIER. Ensuite, téléchargez ce fichier sur votre PC (onglet Fichier -> bouton Plus -> Exporter...) et soumettez vos résultats via l'app Shiny <https://sdd.umons.ac.be/C03Ca_ml_wine> (voir aussi dans le cours en ligne à la section correspondante). NE MODIFIEZ RIEN dans le chunk ci-dessous. -->

```{r results}
results <- predict(my_model, wine2)
table(results)
res_file <- glue::glue("{repos}__{model_name}.rds")
write$rds(results, here::here("results", res_file))
message("Soumettre : results/", res_file)
```
